env:
  global:
   - LIGHTGBM_VERSION=2.3.1

   # travis encrypt GITHUB_OAUTH_TOKEN=<token>
   - secure: "0m7S39+juthWB60etVh/cnY2Beo7dBGWgbF+SSMuvgR3wwjJ5FKL1pD27U+W0S4d9K8cjtqyvDlrHGW4sZR/dHYU+VmfpmId35vAQ/URgxVrjjcHQA7MUORHMd3UmPZc5rvsKjevypYWnryzrH7ele+eY95jUu7UrDxdbXW1tB8GSRT0b+mGib/1b+NghNjCq1IxIDGjAWJnvJDO2B64wGUtgu2mQ4A01Htlj7rrPbolzBETagNGHE5q1Y6TXLvYSWqioefpcKGIl/DhNZ3+FxcwBgx9mEyoE3CWUGK5FV4JbWvR1ZAGA/E7oo9oQ/dnEPgK9jadF22TtP2P2xc7kcgYm4teKwszO+NEf/mxZD+tJxbVUeQ5PemwJm5OjUuVu8XYjSJoMEyWG9HpZXNnGQ4lqO1MWf6ZPkpgxJbIMxksL5M54UXgm7ZUKEyeZU3Rroh4B3KGbFPhhPNkHuRX6+FnI1dZ6TZwlQNflRXLI+TScZWN7oVPOkL/Kmkt0bstSB+IbaLOWY8yBvEm2Tp5OU/lxxdluGdKTv+JA0VVVl5travqzoIcIhaaABIUs1JEFYxt5ffuNV52XFVe8Dc6gEuBxaQwng5PE4hVL1rOpXlanqUkAPhuQo1aUEUc/4BfBLaVfcWh0L1Jxerjr6lrSQyZ7DY3gsC1jx9pJG/O7Rw="

language: java

# Caching so the next build will be fast too.
cache:
  apt: true
  directories:
    - $HOME/.m2
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - os: linux
      sudo: false
      dist: precise
      group: deprecated-2017Q4
      jdk: openjdk7
    - os: osx
      osx_image: xcode10
      jdk: openjdk11

# xcode10 use cmake version 3.12.2, macOS 10.13, JDK 10.0.2+13

notifications:
  email: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get remove -y --purge mongodb;
        sudo rm /etc/apt/sources.list.d/mongodb.list;
        sudo apt-get update;
        sudo apt-get -y install software-properties-common python-software-properties;
        sudo add-apt-repository -y ppa:roblib/ppa;
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
        sudo apt-get update;
    fi
  - if [[ "$TRAVIS_DIST" == "precise" ]]; then
        sudo apt-get update;
        sudo add-apt-repository -y ppa:george-edison55/precise-backports;
        sudo add-apt-repository -y ppa:git-core/ppa;
        sudo apt-get update;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew analytics off;
        brew install swig;
    fi

install:
  - if [[ "$TRAVIS_DIST" == "precise" ]]; then
        sudo apt-get install -y binutils git g++-5 make cmake cmake-data libpthread-stubs0-dev swig;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        sh scripts/build_osx.sh;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        CC=`which gcc-5` CXX=`which g++-5` sh scripts/build_linux.sh;
    fi

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file:
    - lightgbm4j-$LIGHTGBM_VERSION-$TRAVIS_OS_NAME-$TRAVIS_DIST.jar
    - lightgbm4j-$LIGHTGBM_VERSION-$TRAVIS_OS_NAME.jar
  on:
    repo: myui/build-lightgbm-java
    tags: true
  skip_cleanup: true # do not delete the built assets
  overwrite: true
