env:
  global:
   - LIGHTGBM_VERSION=3.2.1

# Run only for tagged commit
branches:
  only:
  - master
  - "/^v[0-9\\.]+(-rc[0-9]+)?/"

language: java

# Caching so the next build will be fast too.
cache:
  apt: true
  directories:
    - $HOME/.m2
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      group: deprecated-2017Q4
      jdk: openjdk7
    - os: osx
      osx_image: xcode10.1
      jdk: openjdk11

# xcode10 use cmake version 3.12.2, macOS 10.13, JDK 10.0.2+13

addons:
  homebrew:
    packages:
    - swig
    update: false

notifications:
  email: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get remove -y --purge mongodb;
        sudo rm /etc/apt/sources.list.d/mongodb.list;
        sudo apt-get remove -y --purge cassandra;
        sudo rm /etc/apt/sources.list.d/cassandra.list;
        sudo apt-get remove -y --purge couchdb;
        sudo rm /etc/apt/sources.list.d/couchdb.list;
        sudo apt-get remove -y --purge pgdg;
        sudo rm /etc/apt/sources.list.d/pgdg.list;
        sudo apt-get update;
        sudo apt-get -y install software-properties-common python-software-properties;
        sudo add-apt-repository -y ppa:roblib/ppa;
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
        sudo apt-get update;
    fi
  - if [[ "$TRAVIS_DIST" == "trusty" ]]; then
        sudo apt-get update;
        sudo add-apt-repository -y ppa:git-core/ppa;
        sudo apt-get update;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export HOMEBREW_NO_AUTO_UPDATE=1;
        brew analytics off;
        brew update;
        brew upgrade cmake;
    fi
# CMake 3.16 or higher is required.  You are running version 3.15.5

install:
  - if [[ "$TRAVIS_DIST" == "trusty" ]]; then
        sudo apt-get install -y binutils git g++-5 make cmake3 cmake3-data libpthread-stubs0-dev swig3.0;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        LIGHTGBM_VERSION=`cat LIGHTGBM_VERSION` sh scripts/build_osx.sh;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        CC=`which gcc-5` CXX=`which g++-5` LIGHTGBM_VERSION=`cat LIGHTGBM_VERSION` sh scripts/build_linux.sh;
    fi

deploy:
  provider: releases
  api_key:
    secure: "cQf1noijrQK/8B8UhjsXXmZoshsqh4HX3NnbQv36I3wWJWj4ju6gwQM3R5xtDLdhyN8OgjdsACfqSnZRp3yY3dRXKewU/WOkU2N3x2QCgGQC2hEhV1OXUOao+p4nINZ7RHocOtvthGSpHvx6h2oHp0O4lReU2QlnqvA7fTZUHmvziOjbDtuKNWkjbr8mvWAf/Z9FpU6ZTzdkbybXHZN+Px2ogZEdLLvkzyMVANs18nRuNyojzurnuAslTPl3pLw4AOHt9luXmw7U9kJstcX6danHzBdSptARxyPiaodQ9rWyg1OLuYcHixWI8l0mSCfvfqQqr4z+4SW+fxW2p/W6miR1mBfMxyysje/pTQ/zZiaCgQxoI7c6joxDXjFNscJkhTK8db6IMj0kjMLdx/uIuuxhmHXsUjCtVgADW0YmQ4C/xdDiHYWfzgFcxWQwfMPUxGDFBhkOuf79Lpx9i/U7Zgkkh+zbVpkgLgm9MY1wObbP6dLl0RwCLsjfSJWYSqPBeIdoKJoBpRSSmEmKwtdstaGOBQSc8iykCONNfNvcHPPvnASVKoym8JfIsivZ9l3ld8c5C+qM/8fclm5AnhQ7NP08lxXP76/pAacz5WaOk40YdKFMiTkSqsqeCayNqLsxau/A+zfIsOHLTsYIa2Ee8Pxu5xvpO1jYChd+aihpqYk="
  file:
    - lightgbm-$LIGHTGBM_VERSION-$TRAVIS_OS_NAME-$TRAVIS_DIST.jar
    - lightgbm-$LIGHTGBM_VERSION-$TRAVIS_OS_NAME.jar
    - lightgbm-$LIGHTGBM_VERSION-sources.jar
    - lightgbm-$LIGHTGBM_VERSION-javadoc.jar
  on:
    repo: myui/build-lightgbm-java
    tags: true
  skip_cleanup: true # do not delete the built assets
  overwrite: true
