env:
  global:
   - LIGHTGBM_VERSION=2.3.1

   # travis encrypt -r myui/build-lightgbm-java --org GITHUB_OAUTH_TOKEN=<token>
   - secure: "pVfZtIPt0nMe5b8Q8aSBAIverSnXb3wjXgN04HEWx+I95RqLR1Fgcl8wxlTa0VC89mk5+g3oR//6Jq6cTf0XmZLja85PL89cSrLLRlZFRk7FJxLOc85gby5Z//p6FC1MFoOugv+g9wz4Kfwmk2i2hPpK44j0AzQkyUAzn/RC3fsXGjjfLY+u1tD7p2zOY8Amc6KpI1MuHDn/xzO3/hxvkgG29t8JwKRsyeoPXuTP3Hs7+8zocth+I4I/NCZGEwyZH+GOAwRW/oMt7XohK8q7UtMBy9H7bU+JWEHQ7g1SPgp9G7dLg+HoZPTM+pdzZ2mnwRuRPndAqGuMxT3t2XryuOys/XBnNarg6GQZ1agMCUjvC2lxF7MKyKrwvq9v1bNR8/ZBzvBt5fay3ZGmNYIBplKY+GVdr8c6EQ6dGVvdG2uwHqyaqJXdBkfMRLGAYXBGhmRIvBIJx/jkjSMT5uSaNA9aVr2sDO8RGtuaioh3myw0bCwNPwwVdeVHmZR66eQPbkVki9GVhHCQMwKQihpqOTJQR1BQHpszWPUHOmbGCxgaQ7taeuLOoZ09JEVLJrXJmfEN0mQFllZS8aD3ya1RSUlW1xQMaUzVPghb/eQrLMBfXfzWi/uOEzU6Po8E5O0bPm5KPy9qQtZ0oj0swGHGURRxbsKrNYZaAhh6Y0f9jiA="

language: java

# Caching so the next build will be fast too.
cache:
  apt: true
  directories:
    - $HOME/.m2
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - os: linux
      sudo: false
      dist: precise
      group: deprecated-2017Q4
      jdk: openjdk7
    - os: osx
      osx_image: xcode10
      jdk: openjdk11

# xcode10 use cmake version 3.12.2, macOS 10.13, JDK 10.0.2+13

notifications:
  email: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get remove -y --purge mongodb;
        sudo rm /etc/apt/sources.list.d/mongodb.list;
        sudo apt-get update;
        sudo apt-get -y install software-properties-common python-software-properties;
        sudo add-apt-repository -y ppa:roblib/ppa;
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
        sudo apt-get update;
    fi
  - if [[ "$TRAVIS_DIST" == "precise" ]]; then
        sudo apt-get update;
        sudo add-apt-repository -y ppa:george-edison55/precise-backports;
        sudo add-apt-repository -y ppa:git-core/ppa;
        sudo apt-get update;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew analytics off;
        brew install swig;
    fi

install:
  - if [[ "$TRAVIS_DIST" == "precise" ]]; then
        sudo apt-get install -y binutils git g++-5 make cmake cmake-data libpthread-stubs0-dev swig;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        sh scripts/build_osx.sh;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        CC=`which gcc-5` CXX=`which g++-5` sh scripts/build_linux.sh;
    fi

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - lightgbm4j-$LIGHTGBM_VERSION-$TRAVIS_OS_NAME-$TRAVIS_DIST.jar
    - lightgbm4j-$LIGHTGBM_VERSION-$TRAVIS_OS_NAME.jar
  on:
    repo: myui/build-lightgbm-java
    tags: true
  skip_cleanup: true # do not delete the built assets
  overwrite: true
